/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialWorkersRouteImport } from './routes/_social-workers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialWorkersEditaisIndexRouteImport } from './routes/_social-workers/editais/index'
import { Route as SocialWorkersConsultarIvsIndexRouteImport } from './routes/_social-workers/consultar-ivs/index'
import { Route as AnalisarInscricaoSubscriptionIdRouteImport } from './routes/analisar.inscricao.$subscriptionId'
import { Route as SocialWorkersEditaisCriarRouteImport } from './routes/_social-workers/editais/criar'
import { Route as SocialWorkersEditaisIdRouteImport } from './routes/_social-workers/editais/$id'
import { Route as SocialWorkersConsultarIvsIdRouteImport } from './routes/_social-workers/consultar-ivs/$id'

const SocialWorkersRoute = SocialWorkersRouteImport.update({
  id: '/_social-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialWorkersEditaisIndexRoute =
  SocialWorkersEditaisIndexRouteImport.update({
    id: '/editais/',
    path: '/editais/',
    getParentRoute: () => SocialWorkersRoute,
  } as any)
const SocialWorkersConsultarIvsIndexRoute =
  SocialWorkersConsultarIvsIndexRouteImport.update({
    id: '/consultar-ivs/',
    path: '/consultar-ivs/',
    getParentRoute: () => SocialWorkersRoute,
  } as any)
const AnalisarInscricaoSubscriptionIdRoute =
  AnalisarInscricaoSubscriptionIdRouteImport.update({
    id: '/analisar/inscricao/$subscriptionId',
    path: '/analisar/inscricao/$subscriptionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SocialWorkersEditaisCriarRoute =
  SocialWorkersEditaisCriarRouteImport.update({
    id: '/editais/criar',
    path: '/editais/criar',
    getParentRoute: () => SocialWorkersRoute,
  } as any)
const SocialWorkersEditaisIdRoute = SocialWorkersEditaisIdRouteImport.update({
  id: '/editais/$id',
  path: '/editais/$id',
  getParentRoute: () => SocialWorkersRoute,
} as any)
const SocialWorkersConsultarIvsIdRoute =
  SocialWorkersConsultarIvsIdRouteImport.update({
    id: '/consultar-ivs/$id',
    path: '/consultar-ivs/$id',
    getParentRoute: () => SocialWorkersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultar-ivs/$id': typeof SocialWorkersConsultarIvsIdRoute
  '/editais/$id': typeof SocialWorkersEditaisIdRoute
  '/editais/criar': typeof SocialWorkersEditaisCriarRoute
  '/analisar/inscricao/$subscriptionId': typeof AnalisarInscricaoSubscriptionIdRoute
  '/consultar-ivs': typeof SocialWorkersConsultarIvsIndexRoute
  '/editais': typeof SocialWorkersEditaisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultar-ivs/$id': typeof SocialWorkersConsultarIvsIdRoute
  '/editais/$id': typeof SocialWorkersEditaisIdRoute
  '/editais/criar': typeof SocialWorkersEditaisCriarRoute
  '/analisar/inscricao/$subscriptionId': typeof AnalisarInscricaoSubscriptionIdRoute
  '/consultar-ivs': typeof SocialWorkersConsultarIvsIndexRoute
  '/editais': typeof SocialWorkersEditaisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_social-workers': typeof SocialWorkersRouteWithChildren
  '/_social-workers/consultar-ivs/$id': typeof SocialWorkersConsultarIvsIdRoute
  '/_social-workers/editais/$id': typeof SocialWorkersEditaisIdRoute
  '/_social-workers/editais/criar': typeof SocialWorkersEditaisCriarRoute
  '/analisar/inscricao/$subscriptionId': typeof AnalisarInscricaoSubscriptionIdRoute
  '/_social-workers/consultar-ivs/': typeof SocialWorkersConsultarIvsIndexRoute
  '/_social-workers/editais/': typeof SocialWorkersEditaisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultar-ivs/$id'
    | '/editais/$id'
    | '/editais/criar'
    | '/analisar/inscricao/$subscriptionId'
    | '/consultar-ivs'
    | '/editais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultar-ivs/$id'
    | '/editais/$id'
    | '/editais/criar'
    | '/analisar/inscricao/$subscriptionId'
    | '/consultar-ivs'
    | '/editais'
  id:
    | '__root__'
    | '/'
    | '/_social-workers'
    | '/_social-workers/consultar-ivs/$id'
    | '/_social-workers/editais/$id'
    | '/_social-workers/editais/criar'
    | '/analisar/inscricao/$subscriptionId'
    | '/_social-workers/consultar-ivs/'
    | '/_social-workers/editais/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocialWorkersRoute: typeof SocialWorkersRouteWithChildren
  AnalisarInscricaoSubscriptionIdRoute: typeof AnalisarInscricaoSubscriptionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_social-workers': {
      id: '/_social-workers'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SocialWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_social-workers/editais/': {
      id: '/_social-workers/editais/'
      path: '/editais'
      fullPath: '/editais'
      preLoaderRoute: typeof SocialWorkersEditaisIndexRouteImport
      parentRoute: typeof SocialWorkersRoute
    }
    '/_social-workers/consultar-ivs/': {
      id: '/_social-workers/consultar-ivs/'
      path: '/consultar-ivs'
      fullPath: '/consultar-ivs'
      preLoaderRoute: typeof SocialWorkersConsultarIvsIndexRouteImport
      parentRoute: typeof SocialWorkersRoute
    }
    '/analisar/inscricao/$subscriptionId': {
      id: '/analisar/inscricao/$subscriptionId'
      path: '/analisar/inscricao/$subscriptionId'
      fullPath: '/analisar/inscricao/$subscriptionId'
      preLoaderRoute: typeof AnalisarInscricaoSubscriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_social-workers/editais/criar': {
      id: '/_social-workers/editais/criar'
      path: '/editais/criar'
      fullPath: '/editais/criar'
      preLoaderRoute: typeof SocialWorkersEditaisCriarRouteImport
      parentRoute: typeof SocialWorkersRoute
    }
    '/_social-workers/editais/$id': {
      id: '/_social-workers/editais/$id'
      path: '/editais/$id'
      fullPath: '/editais/$id'
      preLoaderRoute: typeof SocialWorkersEditaisIdRouteImport
      parentRoute: typeof SocialWorkersRoute
    }
    '/_social-workers/consultar-ivs/$id': {
      id: '/_social-workers/consultar-ivs/$id'
      path: '/consultar-ivs/$id'
      fullPath: '/consultar-ivs/$id'
      preLoaderRoute: typeof SocialWorkersConsultarIvsIdRouteImport
      parentRoute: typeof SocialWorkersRoute
    }
  }
}

interface SocialWorkersRouteChildren {
  SocialWorkersConsultarIvsIdRoute: typeof SocialWorkersConsultarIvsIdRoute
  SocialWorkersEditaisIdRoute: typeof SocialWorkersEditaisIdRoute
  SocialWorkersEditaisCriarRoute: typeof SocialWorkersEditaisCriarRoute
  SocialWorkersConsultarIvsIndexRoute: typeof SocialWorkersConsultarIvsIndexRoute
  SocialWorkersEditaisIndexRoute: typeof SocialWorkersEditaisIndexRoute
}

const SocialWorkersRouteChildren: SocialWorkersRouteChildren = {
  SocialWorkersConsultarIvsIdRoute: SocialWorkersConsultarIvsIdRoute,
  SocialWorkersEditaisIdRoute: SocialWorkersEditaisIdRoute,
  SocialWorkersEditaisCriarRoute: SocialWorkersEditaisCriarRoute,
  SocialWorkersConsultarIvsIndexRoute: SocialWorkersConsultarIvsIndexRoute,
  SocialWorkersEditaisIndexRoute: SocialWorkersEditaisIndexRoute,
}

const SocialWorkersRouteWithChildren = SocialWorkersRoute._addFileChildren(
  SocialWorkersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocialWorkersRoute: SocialWorkersRouteWithChildren,
  AnalisarInscricaoSubscriptionIdRoute: AnalisarInscricaoSubscriptionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
