/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthCadastroRouteImport } from './routes/_auth/cadastro'
import { Route as AppStaffRouteImport } from './routes/_app/_staff'
import { Route as AppEditaisIndexRouteImport } from './routes/_app/editais/index'
import { Route as EditaisIdInscricaoRouteImport } from './routes/editais.$id/inscricao'
import { Route as AnalisarInscricaoSubscriptionIdRouteImport } from './routes/analisar/inscricao_.$subscriptionId'
import { Route as AppEditaisCriarRouteImport } from './routes/_app/editais/criar'
import { Route as AppEditaisIdIndexRouteImport } from './routes/_app/editais/$id/index'
import { Route as AppStaffCoordinatorEquipeRouteImport } from './routes/_app/_staff/_coordinator/equipe'
import { Route as AppStaffSocialWorkersConsultarIvsIndexRouteImport } from './routes/_app/_staff/_social-workers/consultar-ivs/index'
import { Route as AppStaffSocialWorkersConsultarIvsIdRouteImport } from './routes/_app/_staff/_social-workers/consultar-ivs/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/_auth/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisIndexRoute = AppEditaisIndexRouteImport.update({
  id: '/editais/',
  path: '/editais/',
  getParentRoute: () => AppRoute,
} as any)
const EditaisIdInscricaoRoute = EditaisIdInscricaoRouteImport.update({
  id: '/editais/$id/inscricao',
  path: '/editais/$id/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisarInscricaoSubscriptionIdRoute =
  AnalisarInscricaoSubscriptionIdRouteImport.update({
    id: '/analisar/inscricao_/$subscriptionId',
    path: '/analisar/inscricao/$subscriptionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEditaisCriarRoute = AppEditaisCriarRouteImport.update({
  id: '/editais/criar',
  path: '/editais/criar',
  getParentRoute: () => AppRoute,
} as any)
const AppEditaisIdIndexRoute = AppEditaisIdIndexRouteImport.update({
  id: '/editais/$id/',
  path: '/editais/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffCoordinatorEquipeRoute =
  AppStaffCoordinatorEquipeRouteImport.update({
    id: '/_coordinator/equipe',
    path: '/equipe',
    getParentRoute: () => AppStaffRoute,
  } as any)
const AppStaffSocialWorkersConsultarIvsIndexRoute =
  AppStaffSocialWorkersConsultarIvsIndexRouteImport.update({
    id: '/_social-workers/consultar-ivs/',
    path: '/consultar-ivs/',
    getParentRoute: () => AppStaffRoute,
  } as any)
const AppStaffSocialWorkersConsultarIvsIdRoute =
  AppStaffSocialWorkersConsultarIvsIdRouteImport.update({
    id: '/_social-workers/consultar-ivs/$id',
    path: '/consultar-ivs/$id',
    getParentRoute: () => AppStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof AuthCadastroRoute
  '/login': typeof AuthLoginRoute
  '/editais/criar': typeof AppEditaisCriarRoute
  '/analisar/inscricao/$subscriptionId': typeof AnalisarInscricaoSubscriptionIdRoute
  '/editais/$id/inscricao': typeof EditaisIdInscricaoRoute
  '/editais': typeof AppEditaisIndexRoute
  '/equipe': typeof AppStaffCoordinatorEquipeRoute
  '/editais/$id': typeof AppEditaisIdIndexRoute
  '/consultar-ivs/$id': typeof AppStaffSocialWorkersConsultarIvsIdRoute
  '/consultar-ivs': typeof AppStaffSocialWorkersConsultarIvsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof AuthCadastroRoute
  '/login': typeof AuthLoginRoute
  '/editais/criar': typeof AppEditaisCriarRoute
  '/analisar/inscricao/$subscriptionId': typeof AnalisarInscricaoSubscriptionIdRoute
  '/editais/$id/inscricao': typeof EditaisIdInscricaoRoute
  '/editais': typeof AppEditaisIndexRoute
  '/equipe': typeof AppStaffCoordinatorEquipeRoute
  '/editais/$id': typeof AppEditaisIdIndexRoute
  '/consultar-ivs/$id': typeof AppStaffSocialWorkersConsultarIvsIdRoute
  '/consultar-ivs': typeof AppStaffSocialWorkersConsultarIvsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_staff': typeof AppStaffRouteWithChildren
  '/_auth/cadastro': typeof AuthCadastroRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/editais/criar': typeof AppEditaisCriarRoute
  '/analisar/inscricao_/$subscriptionId': typeof AnalisarInscricaoSubscriptionIdRoute
  '/editais/$id/inscricao': typeof EditaisIdInscricaoRoute
  '/_app/editais/': typeof AppEditaisIndexRoute
  '/_app/_staff/_coordinator/equipe': typeof AppStaffCoordinatorEquipeRoute
  '/_app/editais/$id/': typeof AppEditaisIdIndexRoute
  '/_app/_staff/_social-workers/consultar-ivs/$id': typeof AppStaffSocialWorkersConsultarIvsIdRoute
  '/_app/_staff/_social-workers/consultar-ivs/': typeof AppStaffSocialWorkersConsultarIvsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/editais/criar'
    | '/analisar/inscricao/$subscriptionId'
    | '/editais/$id/inscricao'
    | '/editais'
    | '/equipe'
    | '/editais/$id'
    | '/consultar-ivs/$id'
    | '/consultar-ivs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/editais/criar'
    | '/analisar/inscricao/$subscriptionId'
    | '/editais/$id/inscricao'
    | '/editais'
    | '/equipe'
    | '/editais/$id'
    | '/consultar-ivs/$id'
    | '/consultar-ivs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_staff'
    | '/_auth/cadastro'
    | '/_auth/login'
    | '/_app/editais/criar'
    | '/analisar/inscricao_/$subscriptionId'
    | '/editais/$id/inscricao'
    | '/_app/editais/'
    | '/_app/_staff/_coordinator/equipe'
    | '/_app/editais/$id/'
    | '/_app/_staff/_social-workers/consultar-ivs/$id'
    | '/_app/_staff/_social-workers/consultar-ivs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AnalisarInscricaoSubscriptionIdRoute: typeof AnalisarInscricaoSubscriptionIdRoute
  EditaisIdInscricaoRoute: typeof EditaisIdInscricaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/cadastro': {
      id: '/_auth/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_staff': {
      id: '/_app/_staff'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais/': {
      id: '/_app/editais/'
      path: '/editais'
      fullPath: '/editais'
      preLoaderRoute: typeof AppEditaisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/editais/$id/inscricao': {
      id: '/editais/$id/inscricao'
      path: '/editais/$id/inscricao'
      fullPath: '/editais/$id/inscricao'
      preLoaderRoute: typeof EditaisIdInscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisar/inscricao_/$subscriptionId': {
      id: '/analisar/inscricao_/$subscriptionId'
      path: '/analisar/inscricao/$subscriptionId'
      fullPath: '/analisar/inscricao/$subscriptionId'
      preLoaderRoute: typeof AnalisarInscricaoSubscriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/editais/criar': {
      id: '/_app/editais/criar'
      path: '/editais/criar'
      fullPath: '/editais/criar'
      preLoaderRoute: typeof AppEditaisCriarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editais/$id/': {
      id: '/_app/editais/$id/'
      path: '/editais/$id'
      fullPath: '/editais/$id'
      preLoaderRoute: typeof AppEditaisIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_staff/_coordinator/equipe': {
      id: '/_app/_staff/_coordinator/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppStaffCoordinatorEquipeRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/_staff/_social-workers/consultar-ivs/': {
      id: '/_app/_staff/_social-workers/consultar-ivs/'
      path: '/consultar-ivs'
      fullPath: '/consultar-ivs'
      preLoaderRoute: typeof AppStaffSocialWorkersConsultarIvsIndexRouteImport
      parentRoute: typeof AppStaffRoute
    }
    '/_app/_staff/_social-workers/consultar-ivs/$id': {
      id: '/_app/_staff/_social-workers/consultar-ivs/$id'
      path: '/consultar-ivs/$id'
      fullPath: '/consultar-ivs/$id'
      preLoaderRoute: typeof AppStaffSocialWorkersConsultarIvsIdRouteImport
      parentRoute: typeof AppStaffRoute
    }
  }
}

interface AppStaffRouteChildren {
  AppStaffCoordinatorEquipeRoute: typeof AppStaffCoordinatorEquipeRoute
  AppStaffSocialWorkersConsultarIvsIdRoute: typeof AppStaffSocialWorkersConsultarIvsIdRoute
  AppStaffSocialWorkersConsultarIvsIndexRoute: typeof AppStaffSocialWorkersConsultarIvsIndexRoute
}

const AppStaffRouteChildren: AppStaffRouteChildren = {
  AppStaffCoordinatorEquipeRoute: AppStaffCoordinatorEquipeRoute,
  AppStaffSocialWorkersConsultarIvsIdRoute:
    AppStaffSocialWorkersConsultarIvsIdRoute,
  AppStaffSocialWorkersConsultarIvsIndexRoute:
    AppStaffSocialWorkersConsultarIvsIndexRoute,
}

const AppStaffRouteWithChildren = AppStaffRoute._addFileChildren(
  AppStaffRouteChildren,
)

interface AppRouteChildren {
  AppStaffRoute: typeof AppStaffRouteWithChildren
  AppEditaisCriarRoute: typeof AppEditaisCriarRoute
  AppEditaisIndexRoute: typeof AppEditaisIndexRoute
  AppEditaisIdIndexRoute: typeof AppEditaisIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStaffRoute: AppStaffRouteWithChildren,
  AppEditaisCriarRoute: AppEditaisCriarRoute,
  AppEditaisIndexRoute: AppEditaisIndexRoute,
  AppEditaisIdIndexRoute: AppEditaisIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
  AnalisarInscricaoSubscriptionIdRoute: AnalisarInscricaoSubscriptionIdRoute,
  EditaisIdInscricaoRoute: EditaisIdInscricaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
