import type { AuditLog } from "@/types/audit";

export const mockEvents: AuditLog[] = [
  {
    id: 1,
    action: 'NOTICE_CREATED',
    entity_type: 'NOTICE',
    entity_id: 5,
    user: {
      id: 1,
      email: 'coordenador@bea.com',
      full_name: 'Carlos Mendes',
      user_type: 'COORDINATOR',
    },
    description: 'Novo Edital criado',
    metadata: {
      notice_title: 'Edital BEA 2025.1 - Auxílio Permanência',
    },
    created_at: '2025-11-10T09:30:00Z',
  },
  {
    id: 2,
    action: 'REGISTRATION_SUBMITTED',
    entity_type: 'REGISTRATION',
    entity_id: 12,
    user: {
      id: 3,
      email: 'ruan@bea.com',
      full_name: 'Ruan Santos',
      user_type: 'STUDENT',
    },
    description: 'Nova inscrição submetida',
    metadata: {
      notice_title: 'Edital BEA 2025.1 - Auxílio Permanência',
      student_name: 'Ruan Santos',
    },
    created_at: '2025-11-09T13:00:00Z',
  },
  {
    id: 3,
    action: 'DOCUMENT_UPLOADED',
    entity_type: 'DOCUMENT',
    entity_id: 45,
    user: {
      id: 3,
      email: 'ruan@bea.com',
      full_name: 'Ruan Santos',
      user_type: 'STUDENT',
    },
    description: 'Documento enviado',
    metadata: {
      document_name: 'Comprovante de Renda.pdf',
      document_type: 'Comprovante de Renda Familiar',
      file_size: '2.3 MB',
    },
    created_at: '2025-11-09T13:15:00Z',
  },
  {
    id: 4,
    action: 'TEAM_MEMBER_ASSIGNED',
    entity_type: 'TEAM_MEMBER',
    entity_id: 8,
    user: {
      id: 1,
      email: 'coordenador@bea.com',
      full_name: 'Carlos Mendes',
      user_type: 'COORDINATOR',
    },
    description: 'Membro da equipe atribuído',
    metadata: {
      assigned_to: 'Maria Souza',
      role: 'Assistente Social',
    },
    created_at: '2025-11-09T10:00:00Z',
  },
  {
    id: 5,
    action: 'REVIEW_STARTED',
    entity_type: 'REVIEW',
    entity_id: 23,
    user: {
      id: 4,
      email: 'maria@bea.com',
      full_name: 'Maria Souza',
      user_type: 'SOCIAL_WORKER',
    },
    description: 'Análise da inscrição iniciada',
    metadata: {
      student_name: 'João Ferreira',
      status: 'pending',
    },
    created_at: '2025-11-08T14:30:00Z',
  },
  {
    id: 6,
    action: 'REVIEW_APPROVED',
    entity_type: 'REVIEW',
    entity_id: 21,
    user: {
      id: 4,
      email: 'maria@bea.com',
      full_name: 'Maria Souza',
      user_type: 'SOCIAL_WORKER',
    },
    description: 'Inscrição aprovada na análise',
    metadata: {
      student_name: 'Ana Paula Costa',
      status: 'approved',
      comments: 'Documentação completa e família atende aos critérios de vulnerabilidade social.',
    },
    created_at: '2025-11-08T16:45:00Z',
  },
  {
    id: 7,
    action: 'REVIEW_REJECTED',
    entity_type: 'REVIEW',
    entity_id: 19,
    user: {
      id: 6,
      email: 'pedro@bea.com',
      full_name: 'Pedro Lima',
      user_type: 'SOCIAL_WORKER',
    },
    description: 'Inscrição reprovada na análise',
    metadata: {
      student_name: 'Lucas Oliveira',
      status: 'rejected',
      comments: 'Renda familiar per capita acima do limite estabelecido no edital.',
    },
    created_at: '2025-11-07T11:20:00Z',
  },
  {
    id: 8,
    action: 'APPEAL_SUBMITTED',
    entity_type: 'REGISTRATION',
    entity_id: 19,
    user: {
      id: 7,
      email: 'lucas@bea.com',
      full_name: 'Lucas Oliveira',
      user_type: 'STUDENT',
    },
    description: 'Recurso submetido contra decisão',
    metadata: {
      student_name: 'Lucas Oliveira',
      reason: 'Apresentação de novos documentos comprobatórios de renda atualizada.',
    },
    created_at: '2025-11-07T15:00:00Z',
  },
  {
    id: 9,
    action: 'APPEAL_REVIEWED',
    entity_type: 'REGISTRATION',
    entity_id: 19,
    user: {
      id: 1,
      email: 'coordenador@bea.com',
      full_name: 'Carlos Mendes',
      user_type: 'COORDINATOR',
    },
    description: 'Recurso analisado',
    metadata: {
      student_name: 'Lucas Oliveira',
      decision: 'Recurso deferido. Inscrição aprovada após análise de novos documentos.',
    },
    created_at: '2025-11-07T18:30:00Z',
  },
  {
    id: 10,
    action: 'STATUS_CHANGED',
    entity_type: 'REGISTRATION',
    entity_id: 19,
    user: {
      id: 1,
      email: 'coordenador@bea.com',
      full_name: 'Carlos Mendes',
      user_type: 'COORDINATOR',
    },
    description: 'Status da inscrição alterado',
    metadata: {
      old_status: 'Reprovado',
      new_status: 'Aprovado',
    },
    created_at: '2025-11-07T18:31:00Z',
  },
  {
    id: 11,
    action: 'NOTICE_UPDATED',
    entity_type: 'NOTICE',
    entity_id: 4,
    user: {
      id: 1,
      email: 'coordenador@bea.com',
      full_name: 'Carlos Mendes',
      user_type: 'COORDINATOR',
    },
    description: 'Edital atualizado',
    metadata: {
      notice_title: 'Edital BEA 2024.2 - Auxílio Alimentação',
      changes: 'Prazo de inscrição prorrogado até 30/11/2024',
    },
    created_at: '2025-11-06T10:00:00Z',
  },
  {
    id: 12,
    action: 'DOCUMENT_DELETED',
    entity_type: 'DOCUMENT',
    entity_id: 38,
    user: {
      id: 8,
      email: 'fernanda@bea.com',
      full_name: 'Fernanda Rocha',
      user_type: 'STUDENT',
    },
    description: 'Documento removido',
    metadata: {
      document_name: 'Declaracao_antiga.pdf',
      document_type: 'Declaração de Matrícula',
    },
    created_at: '2025-11-06T09:15:00Z',
  },
  {
    id: 13,
    action: 'SOCIAL_WORKER_ANALYSIS',
    entity_type: 'REVIEW',
    entity_id: 25,
    user: {
      id: 4,
      email: 'maria@bea.com',
      full_name: 'Maria Souza',
      user_type: 'SOCIAL_WORKER',
    },
    description: 'Análise social concluída',
    metadata: {
      student_name: 'Carla Mendes',
      status: 'approved',
      comments: 'Visita domiciliar realizada. Situação de vulnerabilidade confirmada.',
    },
    created_at: '2025-11-05T16:00:00Z',
  },
  {
    id: 14,
    action: 'REVIEW_UPDATED',
    entity_type: 'REVIEW',
    entity_id: 23,
    user: {
      id: 4,
      email: 'maria@bea.com',
      full_name: 'Maria Souza',
      user_type: 'SOCIAL_WORKER',
    },
    description: 'Análise atualizada',
    metadata: {
      student_name: 'João Ferreira',
      status: 'pending',
      comments: 'Solicitado complementação de documentos - Certidão de nascimento dos dependentes.',
    },
    created_at: '2025-11-05T11:00:00Z',
  },
  {
    id: 15,
    action: 'NOTICE_DELETED',
    entity_type: 'NOTICE',
    entity_id: 2,
    user: {
      id: 1,
      email: 'coordenador@bea.com',
      full_name: 'Carlos Mendes',
      user_type: 'COORDINATOR',
    },
    description: 'Edital removido',
    metadata: {
      notice_title: 'Edital BEA 2024.1 - Auxílio Moradia (Cancelado)',
    },
    created_at: '2025-11-04T08:00:00Z',
  },
]